[tool.poetry]
name = "blacksheep-server"
version = "0.1.0"
description = ""
authors = ["ppippi <wjdqlsdlsp@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
