line-length = 88
target-version = "py312"

[lint]
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "S",   # flake8-bandit
    "RUF", # ruff-specific rules
    "D",   # pydocstring
    "C90", # mccabe
    "N",   # pep8-naming
    "ANN", # flake8-annotations
    "W",   # Warning
    "C",   # complexity
    "ERA", # eradicate
]
ignore = [
    "D100",  # Missing docstring in public module
    "D104",  # Missing docstring in public package
    "D107",  # Missing docstring in __init__
    "D203",  # 1 blank line required before class docstring
    "D213",  # Multi-line docstring summary should start at the second line
    "D406",  # Section name should end with a newline
    "D407",  # Missing dashed underline after section
    "ANN101",  # Missing type annotation for self in method
    "ANN102",  # Missing type annotation for cls in classmethod
    "ANN002",  # Missing type annotation for *args
    "ANN003",  # Missing type annotation for **kwargs
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.pydocstring]
convention = "google"

[lint.mccabe]
max-complexity = 10

[lint.isort]
combine-as-imports = true
force-wrap-aliases = true

[lint.per-file-ignores]
"tests/*" = ["S101", "ANN", "D"]
"src/db/models/*" = ["D"]
"src/schemas/*" = ["D"]
